#!/usr/bin/env sh

# Notifies Honeybadger of a deploy (or rollback).

# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLES (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME
# KAMAL_COMMAND
# KAMAL_SUBCOMMAND

set -e

REPO_URL=$(git config --get remote.origin.url)

curl https://api.honeybadger.io/v1/deploys -H "X-API-Key: $HONEYBADGER_API_KEY" -H "Content-Type: application/json" -H "Accept: application/json" -d "{\"deploy\":{\"environment\":\"$KAMAL_DESTINATION\",\"local_username\":\"$KAMAL_PERFORMER\",\"revision\":\"$KAMAL_VERSION\",\"repository\":\"$REPO_URL\"}}"

echo "Honeybadger deployment notification complete."
