FROM solr:9.10.1

ADD https://github.com/sul-dlss/sul-solr-configs.git#:argo_prod /myconfig

# Argo schema uses ICU analyzers provided by the Solr analysis-extras module.
ENV SOLR_MODULES=analysis-extras

CMD ["solr-precreate", "argo", "/myconfig", "-Dsolr.config.lib.enabled=true"]
