version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.8.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/lint-erb:
          context: dlss
      - ruby-rails/lint-js
      - ruby-rails/herblint:
          name: herblint
      - ruby-rails/stylelint:
          name: stylelint
      - ruby-rails/test-rails:
          name: test
          context: dlss
          install-chrome: true
          parallelism: 4
          before-test:
            - run:
                name: Set Docker API version
                command: echo 'export DOCKER_API_VERSION=1.44' >> "$BASH_ENV"
            - run:
                name: Prepare for running specs (install JS dependencies and build assets)
                command: bin/rake spec:prepare
            - setup_remote_docker
            # Make sure to set SETTINGS__SOLR__URL to http://solr:8983/solr/argo in CircleCI settings
            - run:
                name: Build and run Solr
                command: |
                  docker build -f Dockerfile-solr -t "argo-b3-solr:latest" .
                  network=`docker network ls --filter label=task-network --format "{{.ID}}"`
                  docker run -d --name solr -p 8983:8983 --network-alias solr --network $network argo-b3-solr:latest
            - run:
                name: Wait for Solr to be ready
                command: dockerize -wait tcp://solr:8983 -timeout 1m
