# Deploy to the stage server.
servers:
  web:
    hosts:
      - argo-b3-stage-a.stanford.edu
  job:
    hosts:
      - argo-b3-stage-a.stanford.edu

# Build natively on the deploy target itself (already has Docker via Puppet)
# rather than emulating amd64 via QEMU on an arm64 developer laptop.
builder:
  remote: ssh://lyberadmin@argo-b3-stage-a.stanford.edu

env:
  clear:
    SETTINGS__SOLR__URL: https://sul-solr.stanford.edu/solr/argo_stage
    SETTINGS__DOR_SERVICES__URL: https://dor-services-stage-lb.stanford.edu
    SETTINGS__PRESERVATION_CATALOG__URL: https://preservation-catalog-stage.stanford.edu
    SETTINGS__STACKS__URL: https://stacks-stage.stanford.edu/image
    SETTINGS__PURL_FETCHER__URL: https://purl-fetcher-stage.stanford.edu
    SETTINGS__PURL__URL: https://sul-purl-stage.stanford.edu
    SETTINGS__ARGO__URL: https://argo-stage.stanford.edu
    SETTINGS__SEARCHWORKS__URL: https://searchworks-preview-stage.stanford.edu
    SETTINGS__EARTHWORKS__URL: https://earthworks-stage.stanford.edu
    SETTINGS__FEATURE_FLAGS__BULK_ACTIONS: true
    SETTINGS__FEATURE_FLAGS__OCR_WORKFLOW: true

    DATABASE_HOSTNAME: argo-b3-db-stage-a

    HONEYBADGER_ENV: stage
