solr:
  url: http://localhost:8983/solr/argo

reload_intervals:
  cocina_model: 10000
  cocina_model_stagger: 1500
  bulk_actions_history: 10000
  workflow_grid: 10000

argo:
  url: https://argo.stanford.edu

google_books_apo: 'druid:bf569gy6501'

dor_services:
  url: "http://localhost:3003"
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4

bulk_actions:
  directory: "tmp/bulk_jobs"

feature_flags:
  bulk_actions: false

stacks:
  url: "http://stacks.stanford.edu/image"

purl:
  url: "https://purl.stanford.edu"

# Gemini API is only used for local development.
gemini_api:
  key: ~

# Vertex AI is used in deployed environments.
vertexai_api:
  key: 'fake-key' # Base64 encoded service account key; actual values from vault/puppet
  project_id: 'sul-ai-sandbox'
  location: 'global'
