# frozen_string_literal: true

module Search
  # Constants for Solr fields
  module Fields
    ACCESS_RIGHTS = 'rights_descriptions_ssimdv'
    APO_DRUID = 'governed_by_ssim'
    APO_TITLE = 'apo_title_ssimdv'
    BARCODES = 'barcode_id_ssimdv'
    BARE_APO_DRUID = 'bare_governed_by_ss'
    BARE_COLLECTION_DRUID = 'bare_member_of_collection_ssm'
    BARE_DRUID = 'druid_bare_ssi'
    COLLECTION_DRUIDS = 'member_of_collection_ssim'
    COLLECTION_TITLES = 'collection_title_ssimdv'
    CONTENT_TYPES = 'content_type_ssimdv'
    DOI = 'doi_ssimdv'
    EARLIEST_ACCESSIONED_DATE = 'accessioned_earliest_dtpsidv'
    EMBARGO_RELEASE_DATE = 'embargo_release_dtpsimdv'
    FILE_ROLES = 'content_file_roles_ssimdv'
    GENRES = 'genre_ssimdv'
    ID = 'id'
    IDENTIFIERS = 'identifier_ssim'
    LANGUAGES = 'sw_language_names_ssimdv'
    LAST_ACCESSIONED_DATE = 'accessioned_latest_dtpsidv'
    LAST_OPENED_DATE = 'opened_latest_dtpsidv'
    LAST_PUBLISHED_DATE = 'published_latest_dtpsidv'
    LICENSES = 'use_license_machine_ssidv'
    METADATA_SOURCE = 'metadata_source_ssimdv'
    MIMETYPES = 'content_file_mimetypes_ssimdv'
    MODS_RESOURCE_TYPES = 'mods_typeOfResource_ssimdv'
    OBJECT_TYPES = 'objectType_ssimdv'
    ORCIDS = 'contributor_orcids_ssimdv'
    OTHER_TAGS = 'exploded_nonproject_tag_ssimdv'
    OTHER_HIERARCHICAL_TAGS = 'hierarchical_other_tag_ssimdv'
    PUBLICATION_DATE = 'publication_year_ssidv'
    PROCESSING_STATUS = 'processing_status_text_ssidv'
    PROJECTS = 'project_tag_ssim'
    PROJECTS_EXPLODED = 'exploded_project_tag_ssimdv'
    PROJECTS_HIERARCHICAL = 'hierarchical_project_tag_ssimdv'
    REGIONS = 'subject_place_ssimdv'
    REGISTERED_DATE = 'registered_dtpsimdv'
    RELEASED_TO = 'released_to_ssim'
    RELEASED_TO_EARTHWORKS = 'released_to_earthworks_dtpsidv'
    RELEASED_TO_PURL_SITEMAP = 'released_to_purl_sitemap_dtpsidv'
    RELEASED_TO_SEARCHWORKS = 'released_to_searchworks_dtpsidv'
    SW_RESOURCE_TYPES = 'sw_resource_type_ssimdv'
    SOURCE_ID = 'source_id_ssi'
    STATUS = 'status_ssi'
    TICKETS = 'ticket_tag_ssim'
    TITLE = 'display_title_ss'
    TOPICS = 'subject_topic_other_ssimdv'
    VERSION = 'current_version_ipsidv'
    WORKFLOW_ERRORS = 'wf_error_ssim'
    WPS_HIERARCHICAL_WORKFLOWS = 'wf_hierarchical_wps_ssimdv'
    WPS_WORKFLOWS = 'wf_wps_ssimdv'
  end
end
