solr:
  url: http://localhost:<%= 8983 + (ENV['TEST_ENV_NUMBER'] || 1).to_i %>/solr/argo

bulk_actions:
  directory: "tmp/bulk_jobs_test"

reload_intervals:
  cocina_model: 500
  cocina_model_stagger: 5
  bulk_actions_history: 500
  workflow_grid: 500
